### ISSUE TITLE
CTRL + W to close script doesn't work when plugin enabled

### ISSUE THREAD

**Issue by nan0m** [Loregret/script-panel-plus#10]
Control + W to close the currently opened script doesn't work with the plugin enabled, instead the top most script is opened

**Comment by Loregret** [comment]
Hi. I added this shortcut to [Godot 4.1 version release](https://github.com/Loregret/script-panel-plus/releases/tag/v.1.3.3).

**Comment by nan0m** [comment]
Thank you! 🙏
