### ISSUE TITLE
No Methods List

### ISSUE THREAD

**Issue by VikingAntics** [Loregret/script-panel-plus#11]
Hi,
I noticed that script-panel-plus removes the Method List/Navigation that is normally present with the default Scripts List.
Are you planning on implementing this functionality into script-panel-plus?

Thanks.

**Comment by Loregret** [comment]
Hi. 

Do you mean this list?
![Screenshot_20230728_152544](https://github.com/Loregret/script-panel-plus/assets/31369647/c365f652-7517-4db7-8ecb-8951e371c5bf)

I added method list to [Godot 4.1 version](https://github.com/Loregret/script-panel-plus/releases/tag/v.1.3.3), but not for 4.0. 

If you need it for 4.0, tell me. I can add it there, too.

**Comment by VikingAntics** [comment]
Awesome!  I'm using 4.1/4.2, so thank you.
