### ISSUE TITLE
Custom Font Size

### ISSUE THREAD

**Issue by Drathal** [Loregret/script-panel-plus#12]
Hi,
i love this plugin, but im missing a config for the font-size. Would it be possible to add a config for he font-sizes?

Edit: I just found out that i can CTRL+Scroll to adjust the font size, but it will reset on project load / restart

**Comment by Loregret** [comment]
> Hi, i love this plugin, but im missing a config for the font-size. Would it be possible to add a config for he font-sizes?
> 
> Edit: I just found out that i can CTRL+Scroll to adjust the font size, but it will reset on project load / restart

Hi. Are you using Godot 4.1? Is your version of the plugin 1.5.3?

**Comment by Loregret** [comment]
![Screenshot_20230913_142225](https://github.com/Loregret/script-panel-plus/assets/31369647/aaaed425-47f0-40d8-8050-779248324302)

Also, do you have the "save session" setting turned on?

**Comment by Loregret** [comment]
I've found the issue and fixed it. Please try the new version out and let me know if it didn't work - https://github.com/Loregret/script-panel-plus/releases/tag/v.1.5.5

**Comment by Drathal** [comment]
Yes i am on Godot 4.1.1. 

Your Update fixes the font scaling. Thanks :)
