### ISSUE TITLE
Context menu position.

### ISSUE THREAD

**Issue by Drathal** [Loregret/script-panel-plus#13]
When I right click on a script, the context menu opens but the x position is not aligned with the Script panel (or mouse). 
It happens on the default editor layout and on custom layouts.

![oqmzID6mGK](https://github.com/Loregret/script-panel-plus/assets/416638/d21ee57a-6afe-4849-990f-bd261c343641)

Godot version: 4.1.1
OS: Windows 11

**Comment by Loregret** [comment]
That's weird. I checked both on Linux and Windows 10, don't have the same issue. 

![Screenshot_20230914_092706](https://github.com/Loregret/script-panel-plus/assets/31369647/4a63502b-81b9-451a-affd-4497b1a06163)

**Comment by Loregret** [comment]
Can you please check this plugin version? I changed get_mouse_position function to alternative.

[script-panel-plus.tar.gz](https://github.com/Loregret/script-panel-plus/files/12605576/script-panel-plus.tar.gz)

**Comment by Loregret** [comment]
@Drathal Can you check this version of the plugin? I changed some of the code, but I don't know if it will fix the issue. Please let me know.

[script-panel-plus.zip](https://github.com/Loregret/script-panel-plus/files/12605670/script-panel-plus.zip)

**Comment by Drathal** [comment]
I tested the new version in a clean new project (Godot 4.1.1).

The behaviour is strange. The First time I right click on a script, the menu is at mouse position. But after that its on x position zero. 

Also I found that the y position is sometimes at zero, sometimes not. 

I disabled my 3 monitor setup (Godot in the middle), but that  did not change anything.

First right click:
![UpeSte1q2T](https://github.com/Loregret/script-panel-plus/assets/416638/679ab665-a1b6-49d0-b34a-63cb48692088)

Second:
![WyXj1NXltr](https://github.com/Loregret/script-panel-plus/assets/416638/413f7faf-8b7b-4185-b3f3-bdf5a55e6114)

Third:
![lENyFvT86E](https://github.com/Loregret/script-panel-plus/assets/416638/fcf15195-0e9d-43ad-9a34-fd786f8c7554)

With big font size:
![mGT6GCZObq](https://github.com/Loregret/script-panel-plus/assets/416638/905bdc76-081f-4b4f-a389-e430faa53fcb)

**Comment by Loregret** [comment]
@Drathal Please, try this version out also.

[script-panel-plus.zip](https://github.com/Loregret/script-panel-plus/files/12605884/script-panel-plus.zip)

**Comment by Loregret** [comment]
@Drathal Can you also try disabling 'embedded subwindows'?

![Screenshot_20230914_103349](https://github.com/Loregret/script-panel-plus/assets/31369647/d4121aec-7ab3-47b9-ac51-43566181f276)

**Comment by Drathal** [comment]
I testes it with  'embedded subwindows' option off. The problem still exist. I also completely closed and reopened the project after changing that setting.

**Comment by Loregret** [comment]
@Drathal Please download the version below and let me know if it fixes the problem. I found some [GitHub issues](https://github.com/godotengine/godot/pull/59108) related to EditorPlugins popups positions. I think it should work.

[script-panel-plus-new.zip](https://github.com/Loregret/script-panel-plus/files/12606203/script-panel-plus-new.zip)

**Comment by Drathal** [comment]
It works!  Perfect, thanks.
