### ISSUE TITLE
Custom Script Documentation Error

### ISSUE THREAD

**Issue by Drathal** [Loregret/script-panel-plus#14]
Godot version: 4.1.1
OS: Windows 11

When I open a documentation that is not from Godot. e.g: "Script Panel Plus" docs. I get many editor rrrors. 

This happen with all "custom" docs.

Open Docs (using F1 Key)
![3gQZnDaDFg](https://github.com/Loregret/script-panel-plus/assets/416638/c9f34bd6-5962-45eb-9b2b-b94f7127d953)

  ```
scene/main/node.cpp:1511 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
  res://addons/script_panel_plus/script_panel/script_panel.gd:489 - Cannot call method 'get_child' on a null value.
  res://addons/script_panel_plus/script_panel/script_panel.gd:343 - Invalid get index 'text' (on base: 'Nil').
  scene/main/node.cpp:1511 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
  res://addons/script_panel_plus/script_panel/script_panel.gd:485 - Cannot call method 'get_child' on a null value.
  res://addons/script_panel_plus/script_panel/script_panel.gd:318 - Invalid get index 'text' (on base: 'Nil').
  res://addons/script_panel_plus/script_panel/script_panel.gd:481 - Out of bounds get index '0' (on base: 'Array[Node]')
  res://addons/script_panel_plus/script_panel/script_panel.gd:265 - Cannot call method 'get_saved_version' on a null value.
  scene/main/node.cpp:1511 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).

```

![uxRWcLUszE](https://github.com/Loregret/script-panel-plus/assets/416638/813274b6-6126-42a0-8596-2062aa41079e)

**Comment by Loregret** [comment]
Custom docs also don't appear on the script list. I'll try to fix it.

**Comment by Drathal** [comment]
Hmm I can see custom Docs in the original Script List:

![un6XTHnKd3](https://github.com/Loregret/script-panel-plus/assets/416638/3ddb3aca-bc2e-4e5b-bba6-36d13e712d1d)

**Comment by Loregret** [comment]
I meant that my Script Panel doesn't show 'Custom Docs' correctly. 

But don't worry, I'm working on it.

**Comment by Loregret** [comment]
@Drathal I solved the issue. Please check the [new version](https://github.com/Loregret/script-panel-plus/releases/tag/v.1.5.9).

**Comment by Drathal** [comment]
Works like a charm!
