### ISSUE TITLE
Feature Request: Original Icons Option

### ISSUE THREAD

**Issue by Drathal** [Loregret/script-panel-plus#15]
I love your editor plugin. 

But I would like if there is an option to use the original Godot icons for the scrips, docs etc.  But i would also understand if thats out of scope :D Then I would just replace the icons for me personally.

New Icons:
![goGhlcuKRV](https://github.com/Loregret/script-panel-plus/assets/416638/39fc063c-dd69-4c59-903b-8cedec46f247)

Godot Icons:
![sQ1TeMNcLj](https://github.com/Loregret/script-panel-plus/assets/416638/cc47c418-3a26-474d-8f66-9d1c447dbcbc)

**Comment by Loregret** [comment]
I implemented *.svg* icons in [new release](https://github.com/Loregret/script-panel-plus/releases/tag/v.1.6.0).

Just replace default icons from 'script_panel/icons/' folder to your own.

**Comment by Drathal** [comment]
Looks great, but i am getting a resource reference error for two icons at every start:
```
 scene/resources/resource_format_text.cpp:447 - res://addons/script_panel_plus/script_panel/script_panel.tscn:5 - ext_resource, invalid UID: uid://d4n28x4moh2t7 - using text path instead: res://addons/script_panel_plus/script_panel/icons/search.svg
  scene/resources/resource_format_text.cpp:447 - res://addons/script_panel_plus/script_panel/script_panel.tscn:6 - ext_resource, invalid UID: uid://darpdb4vvrnxo - using text path instead: res://addons/script_panel_plus/script_panel/icons/menu.svg
```
Deleting the uids from script_panel.tscn solves the problem.
