### ISSUE TITLE
Script List not consistent

### ISSUE THREAD

**Issue by Drathal** [Loregret/script-panel-plus#16]
Version: 1.6.5
Godot: 4.1.1
OS: Windows 11

When I have several Scripts opened. I can close one by right clicking. This script is then removed from the script list. and in the editor.

## behaviour now
When I use the menu bar to close all Scripts `File -> Close All`. 

* The Editor closes all opened scripts. 
* But the script list is not updated.  All scripts are still shown.

When I now change tabs from scripts to another tab (docs) and back
* the script list is empty.

Then opening another script 
* will show all scripts (even closed ones) in the script list.

## expected behaviour 
When I use the menu bar to close all Scripts `File -> Close All`. 

* The Editor closes all opened scripts. 
* The script list is updated.  Script List is empty

When I now change tabs from scripts to another tab (docs) and back
* the script list is empty.

Then opening another script 
* will show only the opened script in the script list.

## Exception for this rule: 
The favourites tab shows all my favourites of course

![Godot_v4 2-dev4_win64_Q2k11IcStP](https://github.com/Loregret/script-panel-plus/assets/416638/59ea8c66-df3f-43ff-904c-8e2e155b89d9)

## motivation
Sometimes I have just to many scripts open. Then I just close all scripts to have a clean script list.

**Comment by Loregret** [comment]
@Drathal Hello there.

I have read your proposal, but I couldn't resolve it in a way you wanted. Try out the [New Release](https://github.com/Loregret/script-panel-plus/releases/tag/v.1.7.0).

I've tried many hours to connect my own functions to the Godot's own MenuBar, but without a result. 

So, buttons in the top menu bar won't work with a plugin's list. So, I just added new buttons to scripts' popup menus. Hopefully, it will be enough for you.

![Screenshot_20230917_161241](https://github.com/Loregret/script-panel-plus/assets/31369647/e1ddfe0c-1c99-480a-b52d-58095ec96834)

**Comment by Drathal** [comment]
@Loregret Thanks for the new version.

The new version really feels good.  

Maybe I have a false intension when i use the favourites. At the moment they are something like session favourites. But then close all scripts should not close favourites. Or it can close them but not remove them from the favourites list. That feels somewhat strange and i personally have no use for favourites as they function now. Because when im unaware, i could accidentally close them all. Also i will lose them when ending a session.

I would now just hide the favourites Tab for me. But then i would like if the `add to favourites` menu entry would also be hidden.

Maybe the favourites could be just a list of favourite files that i could use to open a script, or jump to it. Then this list have to persist as a file.

I am new to Godot especially to writing editor plugins. Maybe i could also toy with it and make a PR for the favourites functionality. 

I hope that helps.

**Comment by Loregret** [comment]
@Drathal Check [this out](https://github.com/Loregret/script-panel-plus/releases/tag/v.1.7.2).

I added an option in Plugin Settings to avoid Favorites from being closed by "Close All", "Close Docs" and "Close Other". It's off by default, because I prefer current behavior more.

Is it acceptable for you?

**Comment by Loregret** [comment]
Also, I use "Add to Favourites" entry without Favourites Tab visible, just to highlight scripts with a :star: icon.

I think giving each popup entry a hiding option is an overkill for now. Maybe I will change my mind in the future, but now I'm against it.

**Comment by Drathal** [comment]
That solution sounds and feels good for me. Thanks for your effort into it.
