### ISSUE TITLE
How I use this where the Script Panel +?

### ISSUE THREAD

**Issue by nielpattin** [Loregret/script-panel-plus#17]
Hi, I just downloaded the addon and enabled it but nothing changed.
Current version is 4.1.1.statble

**Comment by Loregret** [comment]
@neilfranci Hi. Did you open any script? Can you show me a screenshot and debug output of the engine?

**Comment by Loregret** [comment]
I saw in your bio that you use C#. My plugin doesn't work with c# scripts yet. It will show many errors when trying to open any C# script. It's better to use an external code editor with C# scripts.

**Comment by nielpattin** [comment]
> I saw in your bio that you use C#. My plugin doesn't work with c# scripts yet. It will show many errors when trying to open them. I will try to fix it later.

I use the mono version but just use Gdscript in my project from now on. It doesn't show any error and nothing happens.


https://github.com/Loregret/script-panel-plus/assets/66520542/2b313b7c-16f1-4b1d-a085-64996114d806


The fresh project:
[Test.zip](https://github.com/Loregret/script-panel-plus/files/12774179/Test.zip)

**Comment by Loregret** [comment]
@neilfranci That's weird. I need to download Mono version and check it out.

**Comment by Loregret** [comment]
![Screenshot_20230930_104833](https://github.com/Loregret/script-panel-plus/assets/31369647/67e5a268-35fd-4870-b12c-498b225abc99)

@neilfranci I've launched your 'test' project in Mono version and issue didn't show. What happens if your reload the project?

**Comment by Loregret** [comment]
You can also try to delete save file (maybe it has been corrupted somehow):
> addons/script_panel_plus/saves/save <- Delete this file

**Comment by nielpattin** [comment]
@Loregret Weird, I don't have that save file either.

**Comment by Loregret** [comment]
> @Loregret Weird, I don't have that save file either.

It will not be shown in the Editor. You should do it in your File Manager of your OS.

**Comment by nielpattin** [comment]
@Loregret Ahh, I found it, it's because Multiple Window if turned off by me before, reenabled it and it is fixed now.
![image](https://github.com/Loregret/script-panel-plus/assets/66520542/bd8668e8-1eee-42da-893d-496b09c47784)

**Comment by Loregret** [comment]
@neilfranci Didn't know about this. Glad you found the solution.
