### ISSUE TITLE
Feature Request: Remember last scroll position for Docs

### ISSUE THREAD

**Issue by nielpattin** [Loregret/script-panel-plus#18]
When scrolling down the docs it should remember the last scroll position instead of scroll all the way up. 

**Without Plugin, default behavior:**

https://github.com/Loregret/script-panel-plus/assets/66520542/e5df1dd6-1ec7-44ac-9064-e4db7522f6d9

**The Script Panel +Plugin:** 

https://github.com/Loregret/script-panel-plus/assets/66520542/8c421aeb-1812-486f-addb-181dbd40c8e5

### Thanks!

**Comment by Loregret** [comment]
Check the [latest release](https://github.com/Loregret/script-panel-plus/releases/).

I added the requested feature. If you want to turn it off, then uncheck the corresponding setting.

![Screenshot_20230930_114858](https://github.com/Loregret/script-panel-plus/assets/31369647/eb4aa6b6-298a-483d-a4e3-8e02a7dc4547)

**Comment by nielpattin** [comment]
@Loregret Perfect now 🤩
