### ISSUE TITLE
Update to Godot 4.3

### ISSUE THREAD

**Issue by coobenguy** [Loregret/script-panel-plus#23]
Script panel+ will not work with versions of godot past 4.1. Please update. If you try to enable in 4.3 you get this error.

`  scene\gui\tab_bar.cpp:771 - Index p_tab = -1 is out of bounds (tabs.size() = 6).`

**Comment by Loregret** [comment]
@coobenguy I converted the plugin to 4.3, [download latest here](https://github.com/Loregret/script-panel-plus/releases) or wait until it updates on asset library.

**Comment by coobenguy** [comment]
Works perfect, cheers!
