### ISSUE TITLE
Loading from AssetLib tab Errors

### ISSUE THREAD

**Issue by VikingAntics** [Loregret/script-panel-plus#5]
This is really cool asset, but I wanted to let you know there are several errors when installing from the AssetLib tab in Godot 4.1.  They are all related to pathing.  There are still many references in the code to "advanced_script_panel" instead of "script_panel_plus".  Also, there are a couple of error references in the script_panel.tscn file.  Also, the install is missing a "saves" folder.

I managed to repair them all, but you might want to create a new project and do a clean install on your computer to catch and fix them.

Otherwise, it seems like a great utility tool!!!  Thanks!!

**Comment by Loregret** [comment]
Hi. I think I fixed all the issues (or most of them). I renamed the project before uploading it to Asset Library, and then, to my surprise, it was filled with errors. I'm still waiting for Godot Asset Library to accept my bug fix, but for now the version on it is broken.

The save folder bug is also solved in a741059a2f7de6ab3e85e05e94ed917d8165c233.

__

Can you download the [last release](https://github.com/Loregret/script-panel-plus/releases/tag/godot-4.1) and check it for errors?

**Comment by Loregret** [comment]
Checkout the Godot 4.1 version. I moved the Floating Screen button there.

![Screenshot_20230708_015021](https://github.com/Loregret/script-panel-plus/assets/31369647/c7508cd0-a4bd-49a9-ab57-97c619c19a34)

**Comment by VikingAntics** [comment]
Hi.  I think you fixed all of the bugs I was having!  Thanks for getting to it so fast!  This is really a nice plugin.  Even just the colors and icons help a bunch, but the tabs are very convenient.  Great work!
